### ISSUE TITLE
Undefined evaluating sha256Lib.sha256

### ISSUE THREAD

**Issue by artnicbr** [itinance/react-native-sha256#1]
I just installed the lib with yarn and linked. When I try to use it this error message is displayed in a red screen on Expo.
undefined is not and object (evaluating 'sha256Lib.sha')
sha256
sha256.js:12:19

Am I missing something?
Thank you!

**Comment by itinance** [comment]
I am not that Expo-expert but as far as i know, native custom libraries are not supported in expo.
Please turn back here if i am wrong.

**Comment by braianj** [comment]
any solution for this?

**Comment by tattivitorino** [comment]
I think there's no solution apart from creating your app with react-native instead of expo.. I'm facing the same problem.. as far as I know we cant link to native libs with expo.. am I right?
