### ISSUE TITLE
sha256Lib is undefined

### ISSUE THREAD

**Issue by InbarSletean** [itinance/react-native-sha256#6]
While following the installation of the package('yarn add', 'react-native link') , and using the example shown , the app crushes .

Upon further looking into the matter , the sha256Lib is undefined.

*Tested on iOS 10.3 iPhone 6 Simulator*

**Comment by TheLuckyCubes** [comment]
how did you solve?

**Comment by braianj** [comment]
Did you solve this?

**Comment by itinance** [comment]
Have you re-compiled the application after linking?
