### ISSUE TITLE
Filepath and package name missmatch

### ISSUE THREAD

**Issue by G-2-Z** [itinance/react-native-sha256#8]
Filepath to android code is:
`android/src/main/java/com/reactlibrary/`

but java package name is:
`package com.sha256lib;`

Filepath should be changed to 
`android/src/main/java/com/sha256lib/`

**Comment by itinance** [comment]
Th. Fixed with https://github.com/itinance/react-native-sha256/commit/f091b32de3cdd9fc0a995439e905f9d61828db28
